dotenv: .env
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.2'
networks:
  development:
    verify: False
  ganache-gui:
    verify: False
    wallets:
      - ${GANACHE_GUI_PRIVATE_KEY0}
      - ${GANACHE_GUI_PRIVATE_KEY1}
      - ${GANACHE_GUI_PRIVATE_KEY2}
