dotenv: .env
networks:
  development:
    verify: False
  ganache-gui:
    verify: True
    wallets:
      - ${GANACHE_GUI_PRIVATE_KEY0}
      - ${GANACHE_GUI_PRIVATE_KEY1}
      - ${GANACHE_GUI_PRIVATE_KEY2}
