dotenv: .env
networks:
  development:
    verify: False
  ganache-gui:
    verify: False
    brokerContractAddress: 0x602C71e4DAC47a042Ee7f46E0aee17F94A3bA0B6
    wallets:
      - ${GANACHE_GUI_PRIVATE_KEY0}
      - ${GANACHE_GUI_PRIVATE_KEY1}
      - ${GANACHE_GUI_PRIVATE_KEY2}
